# Generated by Django 5.1 on 2024-12-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=20)),
                ('descripcion_categoria', models.CharField(max_length=20)),
                ('activo', models.PositiveSmallIntegerField()),
                ('id_producto', models.PositiveIntegerField()),
            ],
        ),
    ]
