# Generated by Django 5.1 on 2024-12-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('fecha_ingreso', models.DateTimeField()),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_producto', models.CharField(max_length=20)),
                ('stock', models.PositiveIntegerField()),
                ('id_proveedor', models.PositiveIntegerField()),
            ],
        ),
    ]
