# Generated by Django 5.1 on 2024-12-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_venta', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id_cliente', models.PositiveIntegerField()),
                ('fecha_venta', models.DateTimeField()),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_empleado', models.PositiveIntegerField()),
                ('cant_productos', models.PositiveIntegerField()),
                ('id_producto', models.PositiveIntegerField()),
            ],
        ),
    ]
