# Generated by Django 5.1 on 2024-12-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Ventas',
        ),
    ]
